apiVersion: apps/v1
kind: Deployment
metadata:
  name: mascotas-api
  namespace: mascotas-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mascotas-api
  template:
    metadata:
      labels:
        app: mascotas-api
    spec:
      containers:
      - name: mascotas-api
        image: edcamero/mascotas-api:0.0.6
        env:
        - name: DATABASE
          value: mascotas_db
        - name: DATABASE_URL
          value: mongodb+srv://user_db:Mascota12345@mascota.sdg9g.mongodb.net/?retryWrites=true&w=majority
        - name: SECRETKEY
          value: Unipamplona
        - name: ENVIRONMENT_TYPE
          value: P
        imagePullPolicy: Always
        ports:
        - containerPort: 8080