apiVersion: v1
kind: Service
metadata:
  name: mascotas-api
  namespace: mascotas-api
spec:
  selector:
    app: mascotas-api
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080

  type: LoadBalancer