name: CI

on: 
    push:
        paths-ignore:
            - 'frontend/**'
    pull_request:
        paths-ignore:
             - 'frontend/**'
jobs:
    main:
    runs-on: ubuntu-latest
    
    steps:
    -   name: Run a one-line script
        uses: actions/checkout@v2

    -   name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.17

    -   name: Build Go App
        run: go build -v ./...


