name: CI

on: 
    push:
        paths:
            - 'frontend/**'
    pull_request:
        paths:
             - 'frontend/**'

jobs:
  frontend:
    runs-on: ubuntu-latest
    
    steps:
    -   name: Run a one-line script
        uses: actions/checkout@v2

    -   name: Install Vue Dependencias
        run: cd frontend && yarn install
        
    -   name: Check code with EsLint 
        run: cd frontend && yarn lint
    
    -   name: Check code with Prettier
        run: cd frontend && yarn prettier
        
    -   name: Build Vue APP
        run: cd frontend && yarn build

