name: Frontend CI

on: 
    push:
        paths:
            - 'frontend2/**'
    pull_request:
        paths:
             - 'frontend2/**'

jobs:
  frontend:
    runs-on: ubuntu-latest
    
    steps:
    -   name: Run a one-line script
        uses: actions/checkout@v2

    -   name: Install React Dependencias
        run: cd frontend2 && yarn install
        
    -   name: Check code with EsLint 
        run: cd frontend2 && yarn lint
    
    -   name: Check code with Prettier
        run: cd frontend2 && yarn prettier
        
    -   name: Build React APP
        run: cd frontend && yarn build

